[options]
admin_passwd = change_this_master_password
db_host = 10.0.102.57
db_user = odoo
db_password = odoo
db_port = 5432
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/payroll
xmlrpc_interface = 0.0.0.0
dbfilter = ^erpodoo$
