name: Odoo 18 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug runner
        run: |
          whoami
          id
          sudo -l
          which systemctl
          readlink -f $(which systemctl)

      - name: Stop Odoo
        run: sudo /usr/bin/systemctl stop odoo

      - name: Sync project
        run: rsync -av --delete ./ /data/ERP_system-Odoo/

      - name: Install dependencies
        run: |
          source /data/ERP_system-Odoo/venv/bin/activate
          pip install -r /data/ERP_system-Odoo/requirements.txt

      - name: Upgrade modules
        run: |
          /data/ERP_system-Odoo/venv/bin/python /opt/odoo/odoo-bin \
            -c /etc/odoo.conf \
            -d erpodoo \
            -u all \
            --stop-after-init

      - name: Start Odoo
        run: sudo /usr/bin/systemctl start odoo

      - name: Verify Odoo
        run: sudo /usr/bin/systemctl status odoo --no-pager
